# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Installing dependencies
        run: sudo apt-get install -y libssl-dev
          
      # Set secrets on publish.R
      - shell: bash
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
        run: |
          envsubst < visualizations/publish.R.template > visualizations/publish.R

      # Build image
      - name: Building image
        run: |
          cd ./test
          docker build -t shiny-extras .

      # Runs all tests
      - name: Running meta-analysis test
        run: |
          cd ./test/meta-analysis/
          bash run.sh
      
      - name: Running meta-regression mean age test
        run: |
          cd ./test/meta-regression-1/
          bash run.sh
      
      - name: Running meta-regression female test
        run: |
          cd ./test/meta-regression-2/
          bash run.sh
